### ISSUE TITLE
和miui12有兼容问题

### ISSUE THREAD

**Issue by fgprodigal** [yc9559/uperf#1]
锁屏过一会儿解锁后就啥也点不了了

**Comment by Leisuredpootle** [comment]
建议提供更多的相关信息，如机型，MIUI和Android版本号，条件允许的话可以提供logcat和dmesg

**Comment by fgprodigal** [comment]
如何收集logcat日志？

**Comment by grislux55** [comment]
> 如何收集logcat日志？

@fgprodigal https://sspai.com/post/56306

**Comment by fgprodigal** [comment]
最新的release在miui12上好像修复了，我再测一天看看
