### ISSUE TITLE
建議添加超級省電模式，以及新版限制最高頻率的方式

### ISSUE THREAD

**Issue by xup61069** [yc9559/uperf#103]
您好，我在尋找在指定遊戲應用鎖定核心最高頻率來降低發熱的方式，
目前使用scene5手動改頻率達成，但切來切去實在麻煩，還有機會誤操作。

有嘗試編輯uperf.json裡的presets但找不到頻率相關的指令，README好像是v2版的修改方式，
或許能請您告訴我修改那些參數可以達到這個需求呢？
也許可以添加超級省電模式，powersave對我來說仍然非常流暢。
謝謝！
![image](https://user-images.githubusercontent.com/24887063/163939858-c22aef35-c065-4d41-a74a-331790a437aa.png)

**Comment by winfeather24** [comment]
v3已经不能直接限制频率了，可以通过控制功率可以间接控制频率。https://www.coolapk.com/feed/34986119?shareKey=NjMyYzE3YTY3YmY1NjI1ZWE2ODk

**Comment by yc9559** [comment]
推荐修改slowpowerlimit，uperf v3会根据soc的能耗模型选择最优的频率限制😋
