### ISSUE TITLE
Latest update throws errors

### ISSUE THREAD

**Issue by EdelStark** [yc9559/uperf#107]
Latest update throws errors like this on initsvc.log  Is there any problems or should I ignore it? 04/09 build doesn't have this error. I'm using a G90T chipset.

PATH=/data/adb/modules/uperf/bin/busybox:/data/adb/modules/uperf/bin/busybox:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin:/dev/90Q2V
sh=/data/adb/modules/uperf/bin/busybox/sh
sh: write error: Bad address
killall: mi_thermald: no process killed
chmod: /dev/migt: No such file or directory
chmod: /sys/module/migt/parameters/*: No such file or directory
Unable to stop service 'vendor.perfservice'
See dmesg for error reason.
Unable to stop service 'miuibooster'
See dmesg for error reason.
Unable to stop service 'vendor.power-hal-1-0'
See dmesg for error reason.
Unable to stop service 'vendor.power-hal-1-1'
See dmesg for error reason.
Unable to stop service 'vendor.power-hal-1-2'
See dmesg for error reason.
Unable to stop service 'vendor.power-hal-1-3'
See dmesg for error reason.
Unable to stop service 'vendor.power-hal-aidl'
See dmesg for error reason.
Unable to start service 'vendor.power-hal-1-0'
See dmesg for error reason.
Unable to start service 'vendor.power-hal-1-1'
See dmesg for error reason.
Unable to start service 'vendor.power-hal-1-2'
See dmesg for error reason.
Unable to start service 'vendor.power-hal-1-3'
See dmesg for error reason.
Unable to start service 'vendor.power-hal-aidl'
See dmesg for error reason.
sh: write error: Bad address
rmdir: '/dev/cpuset/foreground/boost': Device or resource busy
sh: write error: Invalid argument
sh: write error: Invalid argument

**Comment by yc9559** [comment]
Ignore it please.
