### ISSUE TITLE
22.04.23全面屏手势不正常

### ISSUE THREAD

**Issue by DeanCastiel** [yc9559/uperf#108]
刷了22.04.23后，全面屏手势不能正常使用？禁用后就恢复了

**Comment by railjty** [comment]
请提供系统的logcat日志，dmesg日志，kmsg日志和调度日志

**Comment by DeanCastiel** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by yc9559** [comment]
已在22.05.04修复😋
