### ISSUE TITLE
22.04.23在类原生PEplus上有错误代码

### ISSUE THREAD

**Issue by ICCID0211** [yc9559/uperf#109]
PATH=/data/adb/modules/uperf/bin/busybox:/data/adb/modules/uperf/bin/busybox:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin:/dev/hABEE
sh=/data/adb/modules/uperf/bin/busybox/sh
sh: write error: Invalid argument
sh: write error: Invalid argument
chmod: /proc/sys/kernel/sched_downmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_upmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_downmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_downmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_upmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_downmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_group_downmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_group_upmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_group_downmigrate: Operation not permitted
killall: mi_thermald: no process killed
chmod: /dev/migt: No such file or directory
chmod: /sys/module/migt/parameters/*: No such file or directory
Unable to stop service 'vendor.perfservice'
See dmesg for error reason.
Unable to stop service 'miuibooster'
See dmesg for error reason.
Unable to stop service 'vendor.power-hal-1-0'
See dmesg for error reason.
Unable to stop service 'vendor.power-hal-1-1'
See dmesg for error reason.
Unable to stop service 'vendor.power-hal-1-2'
See dmesg for error reason.
Unable to stop service 'vendor.power-hal-1-3'
See dmesg for error reason.
Unable to stop service 'vendor.power-hal-aidl'
See dmesg for error reason.
Unable to start service 'vendor.power-hal-1-0'
See dmesg for error reason.
Unable to start service 'vendor.power-hal-1-1'
See dmesg for error reason.
Unable to start service 'vendor.power-hal-1-2'
See dmesg for error reason.
Unable to start service 'vendor.power-hal-1-3'
See dmesg for error reason.
Unable to start service 'vendor.power-hal-aidl'
See dmesg for error reason.
sh: write error: Invalid argument
sh: write error: Invalid argument
chmod: /proc/sys/kernel/sched_downmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_upmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_downmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_downmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_upmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_downmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_group_downmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_group_upmigrate: Operation not permitted
chmod: /proc/sys/kernel/sched_group_downmigrate: Operation not permitted
rmdir: '/dev/cpuset/foreground/boost': No such file or directory

**Comment by yc9559** [comment]
已在22.05.04关闭错误日志😋
