### ISSUE TITLE
22.04.23 日志中有很多error 

### ISSUE THREAD

**Issue by wukibaka** [yc9559/uperf#111]
一加5T（骁龙835）
氢10.0.3（安卓10）
[logs.zip](https://github.com/yc9559/uperf/files/8558873/logs.zip)

**Comment by yc9559** [comment]
已在22.05.04关闭错误日志😋

**Comment by wukibaka** [comment]
> 已在22.05.04关闭错误日志😋

sfanalysis的log也还有好多error啊
