### ISSUE TITLE
Pixel 6 Pro

### ISSUE THREAD

**Issue by jacbrooks** [yc9559/uperf#112]
Do these errors affect this module or is still working as normal?

**Comment by jacbrooks** [comment]
[log.zip](https://github.com/yc9559/uperf/files/8575599/log.zip)

**Comment by Kugumin** [comment]
I saw that the dev said to ignore them and check uperf_log.txt if everything is fine

**Comment by yc9559** [comment]
OK if no error in uperf_log.txt.😋
