### ISSUE TITLE
三星note10 9825放一会不动就卡logo

### ISSUE THREAD

**Issue by 234481084** [yc9559/uperf#115]

**Comment by yc9559** [comment]
已在22.05.04修复😋

**Comment by 234481084** [comment]
谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Matt ***@***.***&gt;; 
发送时间: 2022年5月7日(星期六) 晚上8:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yc9559/uperf] 三星note10 9825放一会不动就卡logo (Issue #115)





 
已在22.05.04修复😋
