### ISSUE TITLE
Frequent boosting of little cluster and higher power usage (SD855, MI 9T Pro)

### ISSUE THREAD

**Issue by Kugumin** [yc9559/uperf#119]
So after updating to 22.05.04 I see that little cluster often boosts to 1036 MHz and so stays on it. I am not sure if it's useful to do so and also as per title power usage increased too. App opening speed is better though.

Maybe that's because for `msmnile` config has been changed from powersave governor to schedutil as per update changelog `Added Hybrid CPU Tuning`.

Is it fine to behave like that?

P.S. 22.04.30 seems to be the best in terms of performance and battery at the moment

**Comment by yc9559** [comment]
Fusion CPU scaling seems not as good as expected, so the next version will revert it.😋

**Comment by railjty** [comment]
schedutil and sched are broken by some OEMs currently,especially on MTK devices
