### ISSUE TITLE
DEV 22.05.09 在原神中出现超大核摸鱼现象

### ISSUE THREAD

**Issue by fatpandafafat** [yc9559/uperf#127]
K40游戏增强版，安卓12，V13,0.6.1.29 DEV
芯片：天玑1200 mt6893
超大核在日常时频率基本正常，但进入原神时，超大核频率逐步降低到920mhz左右，并且使用率为 0%，打开背包或者地图时超大核会提升频率并且使用一段时间，然后回到920mhz，不太能确定是什么问题造成的，查看log日志时也没看见报错，所以请大佬看看是什么原因造成的，如果需要日志的话我也会尽力去提供

**Comment by fatpandafafat** [comment]
升级到 DEV 22.05.09 出现的以上问题，DEV 22.05.04 似乎没有出现

**Comment by fatpandafafat** [comment]
现在 4.30 5.4 5.9 均出现原神中超大核摸鱼的情况. 不是很清楚怎么办了。

**Comment by yc9559** [comment]
谢谢反馈，下个版本尝试改进

**Comment by xiaoxue999** [comment]
miui有云控，去了就好了

**Comment by fatpandafafat** [comment]
> miui有云控，去了就好了

试过了，没用

**Comment by fatpandafafat** [comment]
> 谢谢反馈，下个版本尝试改进

前几日升级 uperf 5.20 后运行原神时超大核仍然摸鱼，但在昨天更新新版本MIUI后，运行原神时超大核摸鱼现象似乎消失，超大核使用率正常，而后安装回 uperf 5.9 版本，超大核摸鱼，说明 uperf 5.20 ＋ 最新版本MIUI 能解决该问题
但尚未清楚是MIUI修复BUG或是系统BUG偶发现象，将保留一周该问题，下周开发版公测发包后再进行测试确认相关情况

**Comment by yc9559** [comment]
0509版本漏了一些需要屏蔽的节点，应该是这个问题😋
