### ISSUE TITLE
DEV 22.05.20 Failed to start uperf

### ISSUE THREAD

**Issue by wukibaka** [yc9559/uperf#130]
一加5T 骁龙835 EAS
PE12（安卓12.1）
[logs.zip](https://github.com/yc9559/uperf/files/8739069/logs.zip)

**Comment by railjty** [comment]
![image](https://user-images.githubusercontent.com/30927889/169533903-4bf252cd-9521-4d34-909b-fe3e659edb62.png)
三方内核？还是说这个PE自带调度？

**Comment by wukibaka** [comment]
> ![image](https://user-images.githubusercontent.com/30927889/169533903-4bf252cd-9521-4d34-909b-fe3e659edb62.png)
> 三方内核？还是说这个PE自带调度？

第三方内核

**Comment by degr15** [comment]
![Screenshot_20220522-090647_MiXplorer](https://user-images.githubusercontent.com/46894066/169675761-eae3a720-d1b1-4474-b45c-80d7786aa3e4.png)


I have the same problem with sd732G. I'm using crdroid. This problem doesn't happen on DEV 22.05.09

**Comment by yc9559** [comment]
Will be fixed in the next dev version.😋
