### ISSUE TITLE
DEV 22.05.20 lg g8 sm8150 调度问题

### ISSUE THREAD

**Issue by HZDZ9495** [yc9559/uperf#131]
省电模式下轻度使用gpu频率总是睿到最高频，功耗较高。性能模式下玩游戏（原神）cpu大核频率在2.2g-2.4g波动，很少会睿到最高频，负载也较低，导致帧数不稳定。

**Comment by yc9559** [comment]
这是uperf的特性，低负载倾向于响应速度，高负载倾向于能效比😋

**Comment by HZDZ9495** [comment]
但是老版本 dev22.04.09 恰好相反 在省电模式gpu锁在第二档 性能模式性能释放也更好，cpu能跑满
