### ISSUE TITLE
不自动切换模式

### ISSUE THREAD

**Issue by 466aijq** [yc9559/uperf#138]
版本:uperf v3（20226.5）
用模块自带的自动切换功能，没有secne，不自动切换模式，配置正确，在4月份的版本还是正常的

**Comment by yc9559** [comment]
描述不详细😋

**Comment by 466aijq** [comment]
就是分应用配置模式，模式也是auto，格式也是对的，自从5月20号及以后的版本都是这样，包名和模式都填了，就是没有切换模式的日志，4月30号的版本还是可以正常使用的🤔
