### ISSUE TITLE
miui11.0.3安卓8.1.0的骁龙625已经连续两个版本无法运行uperf了

### ISSUE THREAD

**Issue by yinzhefuyun** [yc9559/uperf#139]
miui11.0.3安卓8.1.0的骁龙625已经连续两个版本无法运行uperf了（[DEV 22.06.05]和[DEV 22.05.20]）
因为没有生成日志文件所以看了下adb提取的日志中可能有用的部分

06-05 20:39:36.468  5849  5849 F libc    : CANNOT LINK EXECUTABLE "/data/adb/modules/uperf/bin/uperf": can't read file "/system/lib64": Is a directory
06-05 20:39:36.471  5849  5849 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 5849 (uperf), pid 5849 (uperf)
06-05 20:39:36.499   998   998 I /system/bin/tombstoned: received crash request for pid 5849
06-05 20:39:36.507  5855  5855 I crash_dump64: performing dump of process 5849 (target tid = 5849)
06-05 20:39:36.508  5855  5855 F DEBUG   : pid: 5849, tid: 5849, name: uperf  >>> /data/adb/modules/uperf/bin/uperf <<<
06-05 20:39:36.552  1667  2109 W NativeCrashListener: Couldn't find ProcessRecord for pid 5849
06-05 20:39:36.468  5849  5849 F libc    : CANNOT LINK EXECUTABLE "/data/adb/modules/uperf/bin/uperf": can't read file "/system/lib64": Is a directory
06-05 20:39:36.471  5849  5849 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 5849 (uperf), pid 5849 (uperf)

06-05 20:39:36.498  5855  5855 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
06-05 20:39:36.499   998   998 I /system/bin/tombstoned: received crash request for pid 5849
06-05 20:39:36.501  3151  3485 W PushService: 2022-06-05 20:39:36,499 - [WARN::PushService] - [Thread:95] JOB: Handle intent action = com.xiaomi.mipush.SEND_MESSAGE
06-05 20:39:36.501  5439  5815 I ##XLogger##: com.miui.cloudservice.securitypush.SecurityContextManager$@IPV6@SourceFile:6, thread:233--pdid: PseudoDeviceId{account='1619*****', id='V2_501***************************f0f51f', timestamp=1654068076490}, current account: 1619*****, valid time: 432000000, now: 1654432776479
06-05 20:39:36.502  5439  5845 I ##XLogger##: com.miui.cloudservice.push.MiPushMessageReceiver::a@SourceFile:8, thread:243--onCommandResult is called, command: register, resultCode: 0, reason: null, category: null
06-05 20:39:36.502  3151  3485 W PushService: 2022-06-05 20:39:36,502 - [WARN::PushService] - [Thread:95] try send mi push message. packagename:com.miui.cloudservice action:Notification
06-05 20:39:36.505  1667  1802 D CompatibilityInfo: mCompatibilityFlags - 0
06-05 20:39:36.505  1667  1802 D CompatibilityInfo: applicationDensity - 440
06-05 20:39:36.505  1667  1802 D CompatibilityInfo: applicationScale - 1.0
06-05 20:39:36.507  5855  5855 I crash_dump64: performing dump of process 5849 (target tid = 5849)
06-05 20:39:36.507  5439  5439 I ##XLogger##: com.miui.cloudservice.securitypush.SecurityPushReceiver::onReceive@SourceFile:2, thread:2--receive: action.sync_security_context_to_mipush_client
06-05 20:39:36.508  5855  5855 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-05 20:39:36.508  5439  5815 I ##XLogger##: com.miui.cloudservice.securitypush.SecurityContextManager$@IPV6@SourceFile:5, thread:233--no need to renew
06-05 20:39:36.508  5855  5855 F DEBUG   : Build fingerprint: 'xiaomi/vince/vince:8.1.0/OPM1.171019.019/V11.0.3.0.OEGCNXM:user/release-keys'
06-05 20:39:36.508  5855  5855 F DEBUG   : Revision: '0'
06-05 20:39:36.508  5855  5855 F DEBUG   : ABI: 'arm64'
06-05 20:39:36.508  5855  5855 F DEBUG   : pid: 5849, tid: 5849, name: uperf  >>> /data/adb/modules/uperf/bin/uperf <<<
06-05 20:39:36.508  5855  5855 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
06-05 20:39:36.509  5439  5825 I ##XLogger##: com.miui.cloudservice.securitypush.@IPV6@SourceFile:1, thread:239--called
06-05 20:39:36.510  5855  5855 F DEBUG   : Abort message: 'CANNOT LINK EXECUTABLE "/data/adb/modules/uperf/bin/uperf": can't read file "/system/lib64": Is a directory'
06-05 20:39:36.510  5439  5825 I ##XLogger##: com.miui.cloudservice.securitypush.@IPV6@SourceFile:8, thread:239--alias simple here
06-05 20:39:36.510  4648  5233 D SyncManagerImpl_flag: sync start
06-05 20:39:36.512  5855  5855 F DEBUG   :     x0   0000000000000000  x1   00000000000016d9  x2   0000000000000006  x3   0000000000000008
06-05 20:39:36.512  5439  5825 I ##XLogger##: com.miui.cloudservice.securitypush.@IPV6@SourceFile:10, thread:239--alias complex here
06-05 20:39:36.512  5855  5855 F DEBUG   :     x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000000020
06-05 20:39:36.512  5855  5855 F DEBUG   :     x8   0000000000000083  x9   45aa1a5bf2b0e428  x10  0000000000000000  x11  0000000000000001
06-05 20:39:36.512  5855  5855 F DEBUG   :     x12  ffffffffffffffff  x13  00000000629ca408  x14  001b0f7d793d8800  x15  0000da2a6c53efe4
06-05 20:39:36.512  5855  5855 F DEBUG   :     x16  0000000000000000  x17  0dee04fe53d180b6  x18  00000000943ed6d7  x19  00000000000016d9
06-05 20:39:36.512  5855  5855 F DEBUG   :     x20  00000000000016d9  x21  0000005ab9ae3091  x22  0000007fc8c883b8  x23  0000005ab9bea238
06-05 20:39:36.512  5855  5855 F DEBUG   :     x24  0000007b9bfa5028  x25  0000007b9bfa5028  x26  0000007fc8c89468  x27  0000007b9c0af7b0
06-05 20:39:36.513  3504  3538 I ActivateInfoStorage: slotId: 1, subId: 2147483644
06-05 20:39:36.513  5855  5855 F DEBUG   :     x28  0000007b9c0af000  x29  0000007fc8c88100  x30  0000007b9c053000
06-05 20:39:36.513  5855  5855 F DEBUG   :     sp   0000007fc8c880c0  pc   0000007b9c05301c  pstate 0000000060000000
06-05 20:39:36.518  5439  5825 I ##XLogger##: com.miui.cloudservice.securitypush.@IPV6@SourceFile:14, thread:239--set alias simple
06-05 20:39:36.519  3504  3538 I ActivateInfoStorage: subId 2147483644 simState not ready : 1
06-05 20:39:36.520  3504  3538 I ActivateService: uid:10103 pid:4265 m:getActivateInfo2 slotId:1 subId:2147483644 ts:64307 onResult not inserted
06-05 20:39:36.521  5439  5845 I ##XLogger##: com.miui.cloudservice.push.MiPushMessageReceiver::a@SourceFile:36, thread:243--register_success
06-05 20:39:36.523  5855  5855 F DEBUG   : 
06-05 20:39:36.523  5855  5855 F DEBUG   : backtrace:
06-05 20:39:36.523  5855  5855 F DEBUG   :     #00 pc 000000000009e01c  /system/bin/linker64 (__dl_abort+104)
06-05 20:39:36.523  5855  5855 F DEBUG   :     #01 pc 000000000001cdc8  /system/bin/linker64 (__dl___linker_init+3872)
06-05 20:39:36.523  5855  5855 F DEBUG   :     #02 pc 0000000000023278  /system/bin/linker64 (_start+4)
06-05 20:39:36.551  5855  5855 E crash_dump64: cannot open libmiuindbg.so: No such file or directory

**Comment by yc9559** [comment]
下个版本改回静态链接，会解决此问题😋
