### ISSUE TITLE
Dev 22.06.05 Failed to start uperf

### ISSUE THREAD

**Issue by WetlandC** [yc9559/uperf#143]
机型：Sony Xperia 1 IV（XQ-CT72）
系统：官方Android12（64.0.A.5.27）
内核：官方内核（5.10.66-android12-9-g39d64f0cba97-ab8335668）
[uperf_log.txt](https://github.com/yc9559/uperf/files/8882680/uperf_log.txt)

Edit：尝试了 DEV 22.04.04 - DEV22.05.20 的所有版本，log 内的报错均为
`E Exception thrown: Failed to get available opp of cpu7`
[uperf_log_520.txt](https://github.com/yc9559/uperf/files/8882779/uperf_log_520.txt)

**Comment by yc9559** [comment]
试试看06.05，增加了生成式频率表😋

**Comment by WetlandC** [comment]
> 试试看06.05，增加了生成式频率表😋

第一个 log（uperf_log.txt）即为 06.05 下的 log，报错不一样但还是 Failed to start uperf

**Comment by yc9559** [comment]
内核可能无法接受CPU频率范围写入😋
