### ISSUE TITLE
天机800U可以用吗

### ISSUE THREAD

**Issue by VMCoud** [yc9559/uperf#145]
天机800U可以用吗

**Comment by JohnCanny52** [comment]
【已支持平台】

高通
骁龙 625/626/660/636/82x/835
骁龙 662/665/675/710/712/730/730g/750g/765/765g/768g/780/778g/778g+
骁龙 845/855/855+/860/865/865+/870/888/888+/8gen1
联发科
Helio P65/G70/G80/G85/G90T
天玑 700/720/800/810/820/900/920/8000/8100
天玑 1000/1000l/1000+/1100/1200/9000
三星
Exynos 8890/8895/9810/9820/9825/990/1080/2100/2200
谷歌
Tensor gs101
