### ISSUE TITLE
大佬，模块调度会影响MIUI12.5的全面屏手势的优先调度吗？

### ISSUE THREAD

**Issue by GRDpengyuyan** [yc9559/uperf#15]
我看过小米的发布会，MIUI已经把全面屏手势的调度给优先化了，不知道大佬的调度是否会影响相关的功能？
![Snipaste_2021-02-02_22-50-15](https://user-images.githubusercontent.com/78254666/106617271-6b5bf880-65a9-11eb-82d3-206742f3fd72.png)

**Comment by yc9559** [comment]
不影响，uperf v2做了跟MIUI官方类似的事
