### ISSUE TITLE
启用模块后Google服务不联网

### ISSUE THREAD

**Issue by Rothes** [yc9559/uperf#150]
Google Play / Google账户登录 没有任何与Google服务器通讯的网络记录
![image](https://user-images.githubusercontent.com/47097395/179547686-d4ce639a-2092-4a76-b30f-8f39f357364e.png)

系统 MIUI 13 v13.0.4.1.45
处理器 天玑8100
模块版本 [DEV 22.07.09](https://github.com/yc9559/uperf/releases/tag/dev-22.07.09)

**Comment by Rothes** [comment]
补充，模块启用后 Google 服务框架 ID 获取为空

**Comment by railjty** [comment]
与Uperf无关

**Comment by Rothes** [comment]
更新至 MIUI v13.0.4.1.51 修复
