### ISSUE TITLE
10Pro。sf会和修改震动的模块冲突

### ISSUE THREAD

**Issue by xzl0326** [yc9559/uperf#159]
不清楚为啥，开启sf后恢复震动模块就失效了。这边贴上恢复震动的模块链接https://cloud.cia.yt/s/z9MsR

**Comment by yc9559** [comment]
目前仍然不清楚post-fs阶段的操作为何会影响振动模块😋

**Comment by xzl0326** [comment]
我目前使用的第三方系统包作者默认已经修改了震动。我自己做了恢复震动的模块，但是开了sf，震动就又变回原来改过的震动。我也不清楚怎么回事。sf工作有日志吗

**Comment by xzl0326** [comment]
[magisk_log_2022-09-16T12.42.27.log](https://github.com/yc9559/uperf/files/9580773/magisk_log_2022-09-16T12.42.27.log)
magisk日志，不确定是否有用。我确定我的震动模块文件替换是成功的。请问有没有什么测试sf的办法

**Comment by xzl0326** [comment]
已使用直接修改vendor分区文件的方式规避这个问题，感谢回答
