### ISSUE TITLE
redmi note 6 pro sdm636 android 11 

### ISSUE THREAD

**Issue by tuleo1** [yc9559/uperf#22]
little cluster is stuck on the lowest frequency and it doesn't change at all, while the big cluster does change and it does go up and down really fast, but little cluster is stuck at lowest freqs
gpu frequency's never change either 
[bug.zip](https://github.com/yc9559/uperf/files/6026110/bug.zip)
^ it has the all the four notes
rom: octavi os 2.0
uperf-dev-21.02.14
edit: another issue that I found is that if u change the frequency of the little cluster manually to max or any other frequency the module will stop changing the big cluster frequency's too

edit: changing the mode to performance from balance fixed the locked frequency of the big cluster but little cluster is still stuck at one frequency and doesn't change at all

**Comment by yc9559** [comment]
Thank you. This is a bug in uperf config generator in DEV 21.02.14, will be fixed in DEV 21.02.28.
