### ISSUE TITLE
想问一下Scene里显示的性能和极速模式有什么区别吗？

### ISSUE THREAD

**Issue by syxf** [yc9559/uperf#23]
想问一下Scene里显示的性能和极速模式有什么区别吗？因为在日志里看这两个其实都是切换到了performance，玩游戏也没感受出太明显的变化......

**Comment by yc9559** [comment]
见模式切换脚本的这一行
https://github.com/yc9559/uperf/blob/ffb36fbeb9eb9604f0101f869e1f033e41a83e60/magisk/script/powercfg_main.sh#L22
