### ISSUE TITLE
redmi note 6 pro cpu freqs stuck (again) 

### ISSUE THREAD

**Issue by tuleo1** [yc9559/uperf#24]
okay so on the latest version 21.02.28 it was working fine and everything till I updated my kernel to mystic x5.1 and the kernel author added something called "sched/uclamp: Add CPU's clamp buckets refcounting" I think this is making the module stop working or like idk but it feels like the module isn't even on, on the older version of the kernel where this uclamp wasn't added the module was fully okay
android 11
kernel mystic x5.1 
[logs.zip](https://github.com/yc9559/uperf/files/6085188/logs.zip)
^ thats the logs if needed

**Comment by yc9559** [comment]
No problem was found in log, please fallback your kernel.
