### ISSUE TITLE
05.23版本导致百度地图打开后系统卡死

### ISSUE THREAD

**Issue by JackCui001** [yc9559/uperf#42]
概率性事件，基本上打开第2-3次就会发生，具体表现为系统睡死，屏幕无变化，按键无反应，只能硬重启。关闭模块后恢复正常。

**Comment by mayhuny** [comment]
小米11，也有相同情况，出现问题的app有百度地图、饿了么。

**Comment by yc9559** [comment]
Fixed in 21.06.20.
