### ISSUE TITLE
安装uperf和qti模块后，selinux被调整为permissive模式

### ISSUE THREAD

**Issue by xigongyue** [yc9559/uperf#43]
机型：小米mix3
MIUI12
面具版本22.0
刷入uperf和qti模块后每次重启selinux都是permissive模式，可否使用Enforcing模式？是否会有其他影响？

**Comment by nkh0472** [comment]
https://github.com/yc9559/uperf/releases/tag/dev-21.05.02
> 新增：标志位系统，包括SELinux、SfAnalysis、SsAnalysis、perfhal-stub开关

https://www.coolapk.com/feed/26711661
> 默认关闭SELinux，可以删除/data/adb/modules/uperf/flags内的标志位恢复

删除flags文件夹里的selinux_permissive文件即可

**Comment by xigongyue** [comment]
thx
