### ISSUE TITLE
Hot Temperature Detected !!!

### ISSUE THREAD

**Issue by Virgosan** [yc9559/uperf#45]
After install the module the phone feeling hot 49/50 celcius after 15 minutes and im trying to play game...i found the issue it because of the system/vendor/etc/perf/common&target make my phone hot after remove it and reflash again my temperature become normal

ps/: My phone is Surya>Snapdragon 732g

**Comment by yc9559** [comment]
Execute `su -c top` to find which process is consuming CPU.

**Comment by Virgosan** [comment]
![Screenshot_2021-07-27-02-44-05-782_com termux](https://user-images.githubusercontent.com/86984048/127042004-f12d0d10-f0cb-4438-be1d-22fbd82d1042.jpg)

**Comment by railjty** [comment]
> ![Screenshot_2021-07-27-02-44-05-782_com termux](https://user-images.githubusercontent.com/86984048/127042004-f12d0d10-f0cb-4438-be1d-22fbd82d1042.jpg)

No process name? Please use adb shell "su -c top"and see which process is consuming CPU
