### ISSUE TITLE
Add eas support (sdm650)

### ISSUE THREAD

**Issue by ogromanas** [yc9559/uperf#47]
Hello, would it be possible to add a config for the sdm650 with eas support?

Recently a kernel with eas support is being implemented. The device is kenzo (xiaomi redmi note 3 snapdragon)

https://github.com/trax85/Citrus-EAS

I would like to thank you for the work of the project. Thank you! I was using it for other kernels on my device, and I would like to be able to continue using it. Thank you again and I'm looking forward to the project!

Spanish user!😉

你好，是否可以为sdm650添加一个支持eas的配置？

最近正在实施一个支持eas的内核。该设备是KENZO（小米红米Note 3 snapdragon）。

https://github.com/trax85/Citrus-EAS

我想感谢你为这个项目所做的工作。Thank you! 我在我的设备上使用它的其他内核，我希望能够继续使用它。再次感谢你，我很期待这个项目!

**Comment by yc9559** [comment]
No problem, sdm650-eas will be add in the next pre-release version, which is expected to be released this Sunday.

**Comment by ogromanas** [comment]
Great!! Thank you @yc9559!!!
