### ISSUE TITLE
panel_uperf is missing | latest Uperf

### ISSUE THREAD

**Issue by WUIX69** [yc9559/uperf#48]
GoodEvening @yc9559

I have an issue regarding the installation of uperf..
I installed successfully the uperf (the latest one) from magisk, but i can't find the panel_uperf in the system.. in that case i can't change performance mode automatically in startup.. 

Device:
Poco M3 (citrus_global)
SnapDragon 662
- running on MIUI | Xiaomi.Eu custom rom

Hope you would fix it soon, Love you 💕

**Comment by yc9559** [comment]
Default power mode is located at `/sdcard/yc/uperf/cur_powermode` in uperf v2. Have a nice a day!
