### ISSUE TITLE
处理器平台识别错误

### ISSUE THREAD

**Issue by 2755337087** [yc9559/uperf#52]
手机用的rom是移植包，导致处理器型号识别成了移植包的处理器

**Comment by alispeedsport** [comment]
Hi
Try this:
1. make backup of build.prop (for if bootloop, restore it)
2. open build.prop & modify  `ro.product.board=×××`  to true chip code or one chip that this mod support.
3. Restart and try to install mod again.
4. If its install done, restart and check is yc folder & log on sdcard or not. If its there, things go right :)

**Comment by yc9559** [comment]
@alispeedsport Thanks.
