### ISSUE TITLE
怎么样才能彻底卸载yc调度

### ISSUE THREAD

**Issue by zhzih** [yc9559/uperf#53]
红米k40pep系统，刷调度模块后，手机几秒钟就会卡一次，卡的时候视频，微信语音都会没声音。现在卸载模块删除yc文件夹后还是这样。
怎么样才能彻底卸载yc调度

红米k40
系统RQ3A.210705.001
PixelExperience_Plus_alioth-11.0-20210728-0923-UNOFFICIAL

**Comment by nkh0472** [comment]
magisk对系统的修改为systemless方式，如果你是用的magisk模块的话，卸载模块并重启后，模块应该不再运行于系统中。

考虑是你系统本身的问题居多，如果不放心的话可以查看magisk日志。

还有可以试图寻找uperf的日志文件，如果重启后不再出现的话应当可以明确模块没有运行。
