### ISSUE TITLE
IQOO z1 天玑1000+ ，播放B站2倍速音画不同步

### ISSUE THREAD

**Issue by das3641** [yc9559/uperf#54]
iqoo z1 ，系统配置8+128 ，屏幕为LCD 144HZ，系统版本1.7.17 。
使用脚本后，balance配置下B站【720p和1080p】2倍速音画不同步，切换性能模式正常；
另外调整全局屏幕刷新率为60 60 144后，西瓜视频和b站的2倍速720及以上分辨率均音画不同步，将对应两包设置为 -1 -1 -1后，西瓜视频恢复正常而b站还是问题依旧。
麻烦看看，谢谢

**Comment by das3641** [comment]
yc调度版本是 DEV 21.07.25

**Comment by yc9559** [comment]
谢谢反馈，已在DEV 22.04.09修复
