### ISSUE TITLE
Pixel 4 XL安装完成自动重启后失效

### ISSUE THREAD

**Issue by RinKaguraaa** [yc9559/uperf#55]
在Magisk管理器中安装模块并重启后，在锁屏界面正常。但解锁手机进入桌面后立刻卡死并自动重启，之后uperf模块被禁用。
SoC是骁龙855，uperf版本是`dev-21.08.15`，Magisk版本是`23.0`。logcat.log日志文件：<https://cowtransfer.com/s/9eeaa93b0aa54d>

**Comment by by9yum** [comment]
我也是一样

**Comment by heddxh** [comment]
我也是。相同机型，相同问题。

**Comment by yc9559** [comment]
uperf dev22.04.23版本会再次尝试解决此问题，若此问题还在，请提供logcat和dmesg日志😋

**Comment by closer233** [comment]
> uperf dev22.04.23版本会再次尝试解决此问题，若此问题还在，请提供logcat和dmesg日志😋

更严重了，重启完直接bootloop，我看看能不能把log提取出来

**Comment by closer233** [comment]
> uperf dev22.04.23版本会再次尝试解决此问题，若此问题还在，请提供logcat和dmesg日志😋

问题仍然存在，而且正常该有log的那个文件夹里根本没有log文件

**Comment by Michael-Altmann** [comment]
Same issue on Pixel 4, and still not fixed in 22.04.23 version. There's no log file in the folder.
在P4上也一样，最近的版本也不行，开机以后只要启动launcher就会重启，文件夹里也没有log😥

**Comment by yc9559** [comment]
已在22.04.30版本修复😋
