### ISSUE TITLE
SDM820 刷入后超频失效，温控已关闭。

### ISSUE THREAD

**Issue by Gokou-Ruri** [yc9559/uperf#6]
启动模式为 performance ，查看 maxfreq 后发现频率上限被锁了。
```
$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
1600000
$ cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
2100000
```
![Screenshot_Simple_System_Monitor_20200906-072418](https://user-images.githubusercontent.com/26711804/92314986-09a35c80-f012-11ea-8e62-17c4ccbe27bb.png)

原本小核心和大核心最大频率应该分别为 1728000 和 2265600 （超频），使用该模块以前CPU频率可以正常超频。
小核和大核频率峰值分别为 1593MHz 和 2150MHz ，即使是玩游戏的时候频率也不能达到最大频率（ 1728MHz 和 2265MHz ）。

所有温控均已关闭（开机自动执行），包括：
```
chmod 400 /vendor/bin/thermal-engine
stop thermal-engine
echo 0 > /sys/module/msm_thermal/core_control/enabled
echo N > /sys/module/msm_thermal/parameters/enabled
echo 0 > /sys/module/msm_thermal/vdd_restriction/enabled
```
CPU无论是在 50℃ 还是 90℃ ，都只能达到 1593MHz 和 2150MHz ，不能超频。

除此以外还发现一些问题，在一些短时高压场景中，大核即使100%负载也依然维持在较低频率，例如点击开始游戏后，游戏画面加载出来的那一瞬间（持续数秒），此时四核负载全都已经100%，但频率却仅仅 1785MHz 或更低。
![Screenshot_画廊_20200906-074734](https://user-images.githubusercontent.com/26711804/92315236-46248780-f015-11ea-92ac-2ca6fdd2199b.png)
![Screenshot_画廊_20200906-075303](https://user-images.githubusercontent.com/26711804/92315295-0f02a600-f016-11ea-8052-60d503a9b344.png)
在禁用 Uperf 的情况下，即使CPU温度达到100℃且负载已满，频率也可以分别维持 1728 和 2265 MHz 不降频（使用 ffmpeg 转码进行测试）。

**Comment by yc9559** [comment]
谢谢反馈。uperf配置生成器考虑了功耗预算，没有给kyro太高的频率上限，选择了一个能够持续运行的频点。uperf随模块提供了一系列默认配置，频点可以自定义，参见项目主页。
