### ISSUE TITLE
找不到/sdcard/yc/uperf/panel_uperf.txt

### ISSUE THREAD

**Issue by LittleYe233** [yc9559/uperf#60]
小米11青春版安装最新版模块，找不到 `panel_uperf.txt` ，手动新建后添加参数也没有效果。现在就是开机默认模式是 powersave ，想设置默认值为 balance ，但没有效果。求解。

**Comment by shiqianwei0508** [comment]
使用scene切换性能模式，这个文件的位置经常变，不同的版本在不同的位置。

**Comment by LittleYe233** [comment]
> 使用scene切换性能模式，这个文件的位置经常变，不同的版本在不同的位置。

那软件内有设置默认模式的地方吗？
