### ISSUE TITLE
K20p刷了后发现无法使用，搞机助手r显示错误。

### ISSUE THREAD

**Issue by Kingsely-o** [yc9559/uperf#63]
rom包为乌堆，内核为魔理沙7月份的。刷了模块后开始是正常，但是后来就无法使用。mt管理器查看模块uperf目录下为空（但实际是有文件的，rec下查看），sdcard目录下uperf文件夹只有5个文件。搞机助手显示模块信息错误有时显示scene附加模块有时是其他的。Magsik重新无法重现刷入模
![4c7030daddee8f134ef40da49fb70a9](https://user-images.githubusercontent.com/52887356/140856360-2ceaf639-b192-45ad-be79-bfcd9f1c7350.jpg)
![79366356fef1215cc4f77a5cfb75fdb](https://user-images.githubusercontent.com/52887356/140856364-5e90938a-e512-4f4c-9143-98ce3b26531e.jpg)
![e0c7d55ede9280479471e61c5429f3f](https://user-images.githubusercontent.com/52887356/140856366-fcef7916-3a77-4af5-96af-a35aca8a603d.jpg)
![068e04f5c901574f034088ebff96d6b](https://user-images.githubusercontent.com/52887356/140856367-753ba780-e9f3-4088-b13c-9b0f588b591b.jpg)
![26a99ef411292b205048996c694cd6e](https://user-images.githubusercontent.com/52887356/140856370-2dc96d52-29ee-48cd-a524-38bfc7167de5.jpg)
块。

**Comment by yc9559** [comment]
请用Magisk安装，搞机助手不在测试范围内
