### ISSUE TITLE
魅族18Pro SM8350 Sfanalysis不工作

### ISSUE THREAD

**Issue by DevHaoZi** [yc9559/uperf#65]
注入日志如下，看起来是成功了，但是并未在运行日志中看到`Surfaceflinger analysis connected`相关日志，由此推测Sfanalysis并未正常工作。
Uperf版本是最新的8.15，Flyme9.2.4最新系统，未关闭SELinux（由Uperf所选择）
`[begin] injecting libsfanalysis.so to /system/bin/surfaceflinger
Injection started...
process: /system/bin/surfaceflinger, libpath: /system/lib64/libsfanalysis.so, pid: 970
Call dlopen("/system/lib64/libsfanalysis.so", RTLD_NOW | RTLD_LOCAL)
Call dlsym(0x35cf285662884f73, "SetSsPid")
Call SetSsPid(1200)
Injection succeeded...
[end]
`

**Comment by yc9559** [comment]
这一点在适配MIUI 13也遇到了，接下来会考虑用模糊分析😋

**Comment by winfeather24** [comment]
貌似为SELinux权限设置不正确造成的「avc: denied { open } for comm="surfaceflinger"」添加了open权限之后就可以正常连接了。

**Comment by yc9559** [comment]
已在Uperf v3修复
