### ISSUE TITLE
SfLag异常触发

### ISSUE THREAD

**Issue by winfeather24** [yc9559/uperf#66]
蓝色的任务是酷安，当时并没有在渲染，但uperf进入了sfboost
![20211121163251](https://user-images.githubusercontent.com/62009531/142755336-97e2895c-4093-43d3-b059-5323fc4346a6.png)

**Comment by winfeather24** [comment]
补充
![QQ截图20211127174919](https://user-images.githubusercontent.com/62009531/143676367-7cd764a6-5cb6-4dae-a685-6062caa47ba8.png)

**Comment by yc9559** [comment]
如果systemui在渲染，也会触发sfboost的😋
