### ISSUE TITLE
添加GPU负载监控

### ISSUE THREAD

**Issue by railjty** [yc9559/uperf#67]
现在YC调度只有CPU负载监视，但是遇到纯GPU场景时无法监视GPU负载，导致CPU频率过低而GPU由于不受管控被系统调度到高频，由此导致功耗上升但是性能没有提升（可见卡顿等）。还有一些SoC如高通骁龙888、骁龙8G1，天玑1200、麒麟9000、Google Tensor/猎户座2100等GPU功耗过高，但是控制频率能有效降低功耗，但即使手动添加相关控制节点，在没有CPU负载时GPU频率总是过低而导致卡顿，但是由系统调度时又因为频率过高而导致高功耗和发热。由此，建议加入GPU负载监控和相应GPU频率控制节点，对GPU这个功耗来源进行合理调度

**Comment by yc9559** [comment]
意思是做用户态的GPU调频吗，这方面高通内核态默认做的已经不错，其他家的我还不太了解，一般做的也还行。此技术的难点在于获取GPU负载，难以归一化😋

**Comment by railjty** [comment]
我是酷安@HamJin
