### ISSUE TITLE
Pixel 6

### ISSUE THREAD

**Issue by jacbrooks** [yc9559/uperf#68]
Unable to install on Pixel 6. Install said raven not supported.

**Comment by railjty** [comment]
Pixel 6 is not supported because we doesn't know how to change the max frequency and min frequency of the CPU

**Comment by jacbrooks** [comment]
I can test some commands if that is what is needed.

**Comment by railjty** [comment]
> I can test some commands if that is what is needed.

Maybe you can use `Scene 5` App on CoolApk and help the author to adapt your device

**Comment by yc9559** [comment]
Pixel is currently not supported due to `/vendor/etc/powerhint.json`
