### ISSUE TITLE
存在卸载残留

### ISSUE THREAD

**Issue by killdayu** [yc9559/uperf#71]
/sdcard/yc/
/data/powercfg.sh*

**Comment by railjty** [comment]
可能将在Uperf v3修复

**Comment by yc9559** [comment]
由于Magisk卸载脚本在/sdcard未解密时工作，这一点可能难以实现

**Comment by railjty** [comment]
> 由于Magisk卸载脚本在/sdcard未解密时工作，这一点可能难以实现

适配Scene调度适配文件可以缓解，不过和Scene强绑定。
