### ISSUE TITLE
如何禁用温控呢？

### ISSUE THREAD

**Issue by 1516265148** [yc9559/uperf#75]
玩游戏更希望CPU能全程不降频，GPU降频没关系，但是CPU降频是真的难受…电池超过40度就开始降频…855大核心降到2.4，中核2.1，全面屏手势都没响应了…
GPU降到最低频都不会这么难受的影响
加个温控开关？或者极速模式CPU不要任何限制？

**Comment by yc9559** [comment]
重复问题
