### ISSUE TITLE
选用极速模式时可以禁止降频吗

### ISSUE THREAD

**Issue by 1516265148** [yc9559/uperf#76]
当电池温度超过40，玩游戏855大核心时不时降到2.4G，疯狂掉帧…实在不懂，为什么要限制频率，而且阈值也太低了吧…

**Comment by winfeather24** [comment]
温控跟调度没有关系，要改善的话删掉温控就好了

**Comment by 1516265148** [comment]
> 温控跟调度没有关系，要改善的话删掉温控就好了

但是禁用模块后，温度再高也不会降频，温控已经都删了，启用模块后调度选performance玩游戏大核心会降到2.4G

**Comment by yc9559** [comment]
默认考虑到机身散热限制，如有需要可更改配置文件中频率限制😋
