### ISSUE TITLE
magisk安装失败

### ISSUE THREAD

**Issue by liuxi378** [yc9559/uperf#77]
[magisk_install_log_2022-03-18T12_41_37.log](https://github.com/yc9559/uperf/files/8301613/magisk_install_log_2022-03-18T12_41_37.log)
![Uploading Screenshot_2022-03-18-12-41-43-522_com.topjohnwu.magisk.jpg…]()

**Comment by yc9559** [comment]
图片无法载入😋

**Comment by liuxi378** [comment]
![Uploading Screenshot_2022-03-24-18-04-20-594_com.topjohnwu.magisk.jpg…]()
