### ISSUE TITLE
Magisk安装失败

### ISSUE THREAD

**Issue by liuxi378** [yc9559/uperf#78]
![机型](https://user-images.githubusercontent.com/60069157/160119588-ca6581da-b2f5-4d80-b449-e3fad69b6163.jpg)
![日志](https://user-images.githubusercontent.com/60069157/160119611-65ad463c-fcd7-4ee2-b80e-8b2a2efe1a66.jpg)
[magisk_install_log_2022-03-18T12_41_37.log](https://github.com/yc9559/uperf/files/8350430/magisk_install_log_2022-03-18T12_41_37.log)
安装失败，试了几次
![微信图片_20220325202108](https://user-images.githubusercontent.com/60069157/160119774-27f6c255-e836-4540-863c-a6e8d6be41a1.jpg)
了

**Comment by Fbk-waifu** [comment]
不支持8gen1

**Comment by yc9559** [comment]
8gen1不在v2的默认支持列表里😋
