### ISSUE TITLE
麻烦问下，后续支持高通695cpu吗

### ISSUE THREAD

**Issue by binterminator** [yc9559/uperf#79]
Hi, is there plans to support the sdm695 高通695 cpu Soc please?
I want to use this amazing module as my phone is getting a serious lagging issue but however, it didn't support my Soc as the terminal told me in the installation.
I would like to see how this module performs on this pretty old Soc, thank you :)

**Comment by yc9559** [comment]
You are allowed to make your own sdm695 config for uperf.
