### ISSUE TITLE
 sys/class/devfreq/ 目录不能被写入调度文件，导致调度一直处于锁定频率情况下运行

### ISSUE THREAD

**Issue by fatpandafafat** [yc9559/uperf#81]
红米K40游戏增强版 天玑1200
安卓12 MIUI13 V13.0.4.1.22.DEV
报错代码：
W Knob '/sys/class/devfreq/mtk-dvfsrc-devfreq/userspace/set_freq' not writeable

**Comment by yc9559** [comment]
谢谢反馈，将在DEV 22.04.09修复
