### ISSUE TITLE
最新版DEV 22.04.04模块，使用的scene动态响应，为什么有时候同一时间有两个重复的记录啊？

### ISSUE THREAD

**Issue by Meteorsss** [yc9559/uperf#84]
最新版DEV 22.04.04模块，使用的scene动态响应，为什么有时候同一时间有两个重复的记录啊？
比如
10:28:11 I Preset inode -> 'powersave'
10:28:24 I Preset inode -> 'balance'
10:28:24 I Preset inode -> 'balance'
10:29:42 I Preset inode -> 'powersave'
10:29:49 I Preset inode -> 'balance'
10:33:16 I Preset inode -> 'powersave'
10:33:18 I Preset inode -> 'balance'
10:35:43 I Preset inode -> 'powersave'
10:39:27 I Preset inode -> 'balance'
10:39:27 I Preset inode -> 'balance'
10:40:02 I Preset inode -> 'powersave'
10:42:09 I Preset inode -> 'balance'
10:42:09 I Preset inode -> 'balance'
10:42:27 I Preset inode -> 'powersave'
10:44:02 I Preset inode -> 'balance'

**Comment by yc9559** [comment]
这是scene的操作
