### ISSUE TITLE
Failed to start uperf

### ISSUE THREAD

**Issue by meiweijia** [yc9559/uperf#86]
Device: Redmi K40 Pro+

OS: PixelExperience_haydn-12.0-20220221-2312-OFFICIAL

Android version: 12

uperf.log: 
16:46:52 I Uperf v3(22.04.04)[5671903], by Matt Yang (yccy@outlook.com)
16:46:52 I Config 'sdm888[22.04.04]' by 'yc@coolapk'
16:46:53 I CpuGovernor cluster0:
16:46:53 I opp  691200 pwr 0.053 cost 0.067
16:46:53 I opp 1094400 pwr 0.092 cost 0.073
16:46:53 I opp 1209600 pwr 0.112 cost 0.081
16:46:53 I opp 1401600 pwr 0.151 cost 0.094
16:46:53 I opp 1497600 pwr 0.184 cost 0.107
16:46:53 I opp 1612800 pwr 0.230 cost 0.124
16:46:53 I opp 1708800 pwr 0.274 cost 0.139
16:46:53 I opp 1804800 pwr 0.323 cost 0.155
16:46:53 I CpuGovernor cluster1:
16:46:53 I opp  710400 pwr 0.136 cost 0.060
16:46:53 I opp 1075200 pwr 0.222 cost 0.065
16:46:53 I opp 1324800 pwr 0.337 cost 0.080
16:46:53 I opp 1670400 pwr 0.560 cost 0.105
16:46:53 I opp 1766400 pwr 0.662 cost 0.117
16:46:53 I opp 1996800 pwr 0.956 cost 0.150
16:46:53 I opp 2227200 pwr 1.327 cost 0.186
16:46:53 I opp 2419200 pwr 1.700 cost 0.220
16:46:53 I CpuGovernor cluster2:
16:46:53 I opp  960000 pwr 0.370 cost 0.096
16:46:53 I opp 1420800 pwr 0.556 cost 0.098
16:46:53 I opp 1670400 pwr 0.768 cost 0.115
16:46:53 I opp 1900800 pwr 0.995 cost 0.131
16:46:53 I opp 2150400 pwr 1.440 cost 0.167
16:46:53 I opp 2380800 pwr 1.955 cost 0.205
16:46:53 I opp 2592000 pwr 2.523 cost 0.243
16:46:53 I opp 2841600 pwr 3.324 cost 0.292
16:46:53 I Loading perapp rule
16:46:53 I Preset 'balance' -> default
16:46:53 I Preset 'balance' -> offscreen
16:46:53 I Preset 'fast' -> 'com.miHoYo.Yuanshen'
16:46:53 I Preset inode -> 'auto'
16:46:53 I Internal perapp switcher enabled
16:46:53 I Perapp '*' -> 'balance'
16:46:53 E Exception thrown: Cannot watch file '/system/lib64/libsurfaceflinger.so'
16:46:53 I Failed to start uperf(pid=6185)

用 root explorer 查看, /system/lib64/libsurfaceflinger.so 文件不存在, 有个比较类似的文件 /system/lib64/libSurfaceFlingerProp.so

**Comment by yc9559** [comment]
将在DEV 22.04.09版本修复
