### ISSUE TITLE
Redmi K50 Pro开机硬重启

### ISSUE THREAD

**Issue by railjty** [yc9559/uperf#88]
Redmi K50 Pro开机进入桌面后触发硬重启，禁用sfanalysis不能解决，禁用uperf并开机后手动执行service.sh正常使用。单独启用sfanalysis并开机后手动执行service.sh正常使用

**Comment by yc9559** [comment]
谢谢反馈，开发机同为Redmi K50 Pro未遇到此问题，请检查环境

**Comment by railjty** [comment]
> 谢谢反馈，开发机同为Redmi K50 Pro未遇到此问题，请检查环境

疑似停用系统svc导致。而且同为K50 Pro，有多次出现息屏重启情况
