### ISSUE TITLE
v3版本的按app自动调整模式是必须搭配scene使用吗？

### ISSUE THREAD

**Issue by suroot66** [yc9559/uperf#90]
我在yc/uperf下面发现了perapp_powermode.txt，里面有一些包名和默认配置，但是发现其并未生效，在log中依然只有手动修改cur_powermode.txt才有模式更改的记录，请问这个是正常的吗？ 是必须搭配scene辅助模式常驻后台才能动态修改调度模式吗？😳

**Comment by railjty** [comment]
不需要，不过cur_powermode必须设置为auto，且禁用Scene-动态响应

**Comment by suroot66** [comment]
> 

okk，明白了，谢谢！
