### ISSUE TITLE
22.04.04版每次开机GPU频率上限都不一样

### ISSUE THREAD

**Issue by Gokou-Ruri** [yc9559/uperf#97]
有时候开机后频率上限是499MHz，有时候开机后是585MHz，有时候开机后是675MHz，但实际上内核有超频到810MHz，但是用了uperf以后就没有810MHz了。
两个附属模块也都装了。

**Comment by yc9559** [comment]
关闭模块重启后，给`/sys/class/kgsl/kgsl-3d0/devfreq/min_freq`写GPU最低频是否也会有一样的结果？
