### ISSUE TITLE
Redmi K50 Series系统增强了对部分关键进程的核心亲和锁定

### ISSUE THREAD

**Issue by railjty** [yc9559/uperf#98]
surfaceflinger、hwc等关键进程重新锁定为小核由息屏后改为几秒内，且通过system_server的API进行，疑似已经绕开/dev/cpuset内的节点。
修改建议：ssAnalysis挂钩修改system_server的cpuset相关API，阻止这种奇怪的行为
不得不说MT6895 6983底层真不行。。。

**Comment by yc9559** [comment]
ssAnalysis基本上弃用了，兼容性问题比较多
